### ISSUE TITLE
Add support for status "postponed"

### ISSUE THREAD

**Issue by geckon** [geckon/hockepy#61]
E.g.
```
{
      "gamePk" : 2019021109,
      "link" : "/api/v1/game/2019021109/feed/live",
      "gameType" : "R",
      "season" : "20192020",
      "gameDate" : "2020-03-15T17:30:00Z",
      "status" : {
        "abstractGameState" : "Preview",
        "codedGameState" : "9",
        "detailedState" : "Postponed",
        "statusCode" : "9",
        "startTimeTBD" : false
      },
      "teams" : {
        "away" : {
          "leagueRecord" : {
            "wins" : 37,
            "losses" : 25,
            "ot" : 9,
            "type" : "league"
          },
          "score" : 0,
          "team" : {
            "id" : 22,
            "name" : "Edmonton Oilers",
            "link" : "/api/v1/teams/22"
          }
        },
        "home" : {
          "leagueRecord" : {
            "wins" : 41,
            "losses" : 21,
            "ot" : 7,
            "type" : "league"
          },
          "score" : 0,
          "team" : {
            "id" : 4,
            "name" : "Philadelphia Flyers",
            "link" : "/api/v1/teams/4"
          }
        }
      },
      "venue" : {
        "id" : 5096,
        "name" : "Wells Fargo Center",
        "link" : "/api/v1/venues/5096"
      },
      "content" : {
        "link" : "/api/v1/game/2019021109/content"
      }
    }
```

**Comment by geckon** [comment]
Probably related:
```
$ ./hocke.py schedule 2020-03-16
Schedule for 2020-03-16
Traceback (most recent call last):
  File "./hocke.py", line 81, in <module>
    run_hockepy()
  File "./hocke.py", line 76, in run_hockepy
    command.run()
  File "/home/theger/ws/priv/hockepy/hockepy/commands/schedule.py", line 180, in run
    self.print_schedule(schedule, local_tz)
  File "/home/theger/ws/priv/hockepy/hockepy/commands/schedule.py", line 151, in print_schedule
    self.print_game(game, team_width, local_tz)
  File "/home/theger/ws/priv/hockepy/hockepy/commands/schedule.py", line 130, in print_game
    score = Schedule.get_score_txt(game, score_fmt)
  File "/home/theger/ws/priv/hockepy/hockepy/commands/schedule.py", line 78, in get_score_txt
    if game.last_play.period == 'SO' or game.last_play.period == 'OT':
AttributeError: 'NoneType' object has no attribute 'period'
```
